### ISSUE TITLE
Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by neumachen** [contino/docker-okta-aws#4]
```
╰─$ dcomp run --rm okta-aws
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:41)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
        at com.okta.tools.awscli.main(awscli.java:41)
```

**Comment by neumachen** [comment]
How can this be fixed?

**Comment by lucasteligioridis** [comment]
Is this an issue with the version of the JDK this image is based on?

Can you give a little bit more information as to what you are doing here please?

**Comment by mcameron** [comment]
In `~/.okta/config.properties` what is your `OKTA_BROWSER_AUTH` setting?

**Comment by neumachen** [comment]
@lucas044 I think so. I'm just running the image and that error pops up.

**Comment by neumachen** [comment]
@mcameron I don't have one?

**Comment by lucasteligioridis** [comment]
@magicalbanana what does your `~/.okta/config.properties` look like?
Or are you passing in environment variables?

At a minimum you need the `OKTA_ORG` and the `OKTA_AWS_APP_URL` variables to be passed into the container as stated in the documentation:
https://github.com/contino/docker-okta-aws#environment-variables
